## Source: https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana-oss:6.2.3

## Source:https://github.com/johtani/analyze-api-ui-plugin
RUN kibana-plugin install https://github.com/johtani/analyze-api-ui-plugin/releases/download/6.2.3/analyze-api-ui-plugin-6.2.3.zip
## Source: https://github.com/bahaaldine/topology
RUN kibana-plugin install https://github.com/bahaaldine/topology/releases/download/major.minor.patch/topology-major.minor.patch.zip
## Source: https://github.com/sirensolutions/sentinl
RUN kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.2/sentinl-v6.2.2.zip
