#Source: https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3

# installing ingest-geoip plugin
# RUN elasticsearch-plugin install ingest-geoip
